spring:
  datasource:
    username: ${DATASOURCE_USERNAME:compose-postgres}
    password: ${DATASOURCE_PASSWORD:compose-postgres}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/compose-postgres}
  jpa:
    hibernate.ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
server:
  port: ${SERVER_PORT:8080}